drop table user if exists ;
create table user(
    id bigint generated by default as identity ,
    username VARCHAR (40),
    name VARCHAR (20),
    age int(3)
    balance decimal (10,2),
    primary key (id)
);