server:
  port: 6002
spring:
  application:
    name: springbootConfig
  profiles:
    active: subversion
  cloud:
    config:
      server:
        svn:
          uri: file:///D:/WS/test
          #username: ynsun
          #password: sqy199867
          default-label:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30


